appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: tB5I4iTBSrUm0GIkOcOwYp9bfFLAyNaSk6aQvoDAy+c6R4BwLMQX9OnDTZH/Ad/UAVxi+qew5MbZ3hvMyRhsdPgIqgEHLY5bnRYVg8Ex9kflAF4Ep+Qs7T8D2ZgNVuZDv9nNRh5lG0WS964Yw8ASimfTOWaRAe1yvAOkO2aWHs+RUfIr8JRB3j8KxnfUKeftmwrEEPysUOYKRdx2wPn+l91cziAa2P4BMKQMZng2SOErd3XltLU8ObgUQ8aUcNrKXTXTFkhIg0xBg7Llhu+g+snSBM1OMhtwgkSErLQBMnO0HVvekKqavoSdxX96fp0a9X52A6OmW5H/QVgaJYgZ5ltfyHzDeT9l1JJ6LYZ0zJzZ4zf51oEY2NjKSbMWqxEarDtyZX0UWHVo9A9cKNj+l3DUr0d5ptat6xb6EbTwBNKCuR86oOeLklmC0esrNaS0upTTLcQGwjER6OGzl9h4D6AEPhXpTOKNQgECmUiQIcSR4adpYYuCga+mFhMmBxkh7p8VqvJmwPwqq57F3ljEUrBor/YamdQQzp6hpKYGmRFLMTyjDX3tN26l4RBDYwdtrQvn4cweG8eqKo1D4AvtRWZbEsjt3AbuWN/76tojax7Ep2HeZKa2RlzWaw4Cguy0FFLBLmmaaM7DjkkFrMR9hEsm4u9v4WkEcTlfJY7mA8g=}
provider:
  win: azure
